sudo: required

language: generic

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
#            - clang-format
            - g++-5
            - libboost-all-dev
            - libglew-dev
            - xorg
            - xorg-dev
            - libglu1-mesa-dev
            - libopencv-dev
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

notifications:
  email: false

before_install:
  - apt-cache search clang-format
  - git submodule update --init --recursive
  - eval "${MATRIX_EVAL}"

install:
  - git clone https://github.com/glfw/glfw.git
  - cd glfw
  - mkdir build
  - cd build
  - cmake -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX ..
  - sudo make install -j${nproc}
  - sudo ldconfig

script:
  - cd ../..
  - mkdir build && cd build
  - cmake -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX ..
  - make -j${nproc}
  - ctest
