sudo: required

language: cpp

install:
  - sudo apt-get install libboost-all-dev
  - sudo apt-get install libglew-dev
  - git clone https://github.com/glfw/glfw.git
  - mkdir build && cd build
  - cmake ../glfw
  - make -j4
  - sudo make install

script:
  - cd master
  - cmake .
  - make
