sudo: required

notifications:
  email: false

addons:
  apt:
    packages:
      - libboost-all-dev
      - libglew-dev
      - xorg
      - xorg-dev
      - libglu1-mesa-dev
      - python3-pip
      - opencv-python

install:
  - sudo pip3 install Pillow
  - sudo pip3 install matplotlib
  - sudo pip3 install numpy
  - sudo pip3 install pytesseract
  - git clone https://github.com/glfw/glfw.git
  - cd glfw
  - mkdir build
  - cd build
  - cmake ..
  - sudo make install
  - sudo ldconfig

script:
  - cd ../..
  - cmake .
  - make
