sudo: required

notifications:
  email: false

addons:
  apt:
    packages:
      - libboost-all-dev
      - libglew-dev
      - xorg
      - xorg-dev
      - libglu1-mesa-dev
      - python3-pip
      - python-opencv
      - python3-tk

install:
  - sudo pip3 install Pillow
  - sudo pip3 install matplotlib
  - sudo pip3 install numpy
  - sudo pip3 install pytesseract
  - git clone https://github.com/glfw/glfw.git
  - cd glfw
  - mkdir build
  - cd build
  - cmake ..
  - sudo make install
  - sudo ldconfig
  - cd ../..
  - wget https://github.com/opencv/opencv/archive/3.4.0.zip
  - unzip 3.4.0.zip
  - cd opencv-3.4.0
  - mkdir build
  - cd build
  - cmake -DWITH_QT=ON -DWITH_OPENGL=ON -DFORCE_VTK=ON -DWITH_TBB=ON -DWITH_GDAL=ON -DWITH_XINE=ON -DBUILD_EXAMPLES=ON -DENABLE_PRECOMPILED_HEADERS=OFF ..
  - make -j4
  - sudo make install
  - sudo ldconfig

script:
  - cd ../..
  - cmake .
  - make
