sudo: required

notifications:
  email: false

addons:
  apt:
    packages:
      - libboost-all-dev
      - libglew-dev
      - xorg
      - xorg-dev
      - libglu1-mesa-dev
      - python3-pip

install:
  - sudo pip3 install Pillow > /dev/null
  - sudo pip3 install matplotlib > /dev/null
  - sudo pip3 install numpy > /dev/null
  - sudo pip3 install opencv-python > /dev/null
  - sudo pip3 install pytesseract > /dev/null
  - git clone https://github.com/glfw/glfw.git
  - cd glfw
  - mkdir build
  - cd build
  - cmake ..
  - sudo make install
  - sudo ldconfig

script:
  - cd ../..
  - cmake .
  - make
