sudo: required

language: cpp

install:
  - sudo apt-get install libboost-all-dev
  - sudo apt-get install libglew-dev
  - git clone https://github.com/glfw/glfw.git
  - cd glfw
  - mkdir build
  - cd build
  - cmake ..
  - sudo make install
  - sudo ldconfig

script:
  - cd master
  - cmake .
  - make
