sudo: required

language: generic

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libboost-all-dev
            - libglew-dev
            - xorg
            - xorg-dev
            - libglu1-mesa-dev
            - libopencv-dev
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang++-3.8
            - libboost-all-dev
            - libglew-dev
            - xorg
            - xorg-dev
            - libglu1-mesa-dev
            - libopencv-dev
      env:
        - MATRIX_EVAL="CC=clang-3.8 && CXX=clang++-3.8"

notifications:
  email: false

before_install:
  - git submodule update --init --recursive
  - eval "${MATRIX_EVAL}"

install:
  - git clone https://github.com/glfw/glfw.git
  - cd glfw
  - mkdir build
  - cd build
  - cmake ..
  - sudo make install
  - sudo ldconfig

script:
  - cd ../..
  - mkdir build && cd build
  - cmake ..
  - make
  - ctest
