sudo: required

language: cpp

compiler:
  - gcc
  - g++
  - clang
  - llvm

install:
  - sudo apt-get install libboost-all-dev
  - sudo apt-get install freeglut3-dev

script:
  - cd master
  - cmake .
  - make
