sudo: required

notifications:
  email: false

install:
  - sudo apt-get install libboost-all-dev
  - sudo apt-get install libglew-dev
  - sudo apt-get install xorg
  - sudo apt-get install xorg-dev
  - sudo apt-get install libglu1-mesa-dev
  - sudo apt-get install python3-pip
  - sudo pip3 install Pillow
  - sudo pip3 install matplotlib
  - sudo pip3 install numpy
  - sudo pip3 install opencv-python
  - sudo pip3 install pytesseract
  - git clone https://github.com/glfw/glfw.git
  - cd glfw
  - mkdir build
  - cd build
  - cmake ..
  - sudo make install
  - sudo ldconfig

script:
  - cd ../..
  - cmake .
  - make
