sudo: required

language: cpp

install:
  - sudo apt-get install libboost-all-dev
  - sudo apt-get install libXmu-dev libXi-dev libgl-dev dos2unix git wget

script:
  - cd master
  - cmake .
  - make
