sudo: required

language: generic

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libboost-all-dev
            - libglew-dev
            - xorg
            - xorg-dev
            - libglu1-mesa-dev
            - libopencv-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang++-6
            - libboost-all-dev
            - libglew-dev
            - xorg
            - xorg-dev
            - libglu1-mesa-dev
            - libopencv-dev
      env:
        - MATRIX_EVAL="CC=clang-6 && CXX=clang++-6"

notifications:
  email: false

before_install:
  - git submodule update --init --recursive
  - eval "${MATRIX_EVAL}"

install:
  - git clone https://github.com/glfw/glfw.git
  - cd glfw
  - mkdir build
  - cd build
  - cmake -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX ..
  - sudo make install -j${nproc}
  - sudo ldconfig

script:
  - cd ../..
  - mkdir build && cd build
  - cmake -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX ..
  - make -j${nproc}
  - ctest
