sudo: required

language: cpp

notifications:
  email: false

addons:
  apt:
    packages:
#      - libboost-all-dev
#      - libglew-dev
#      - xorg
#      - xorg-dev
#      - libglu1-mesa-dev
      - python3-pip
      - python3-tk
      - python-opencv
      - python-numpy

install:
#  - sudo pip3 install matplotlib
  - sudo pip3 install Pillow
  - sudo pip3 install pytesseract
#  - git clone https://github.com/glfw/glfw.git
#  - cd glfw
#  - mkdir build
#  - cd build
#  - cmake ..
#  - sudo make install
#  - sudo ldconfig

script:
#  - cd ../..
  - cmake .
  - make
