sudo: required

language: generic

matrix:
  include:
    - os: linux
      addons:
        apt:
          source:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

notifications:
  email: false

addons:
  apt:
    packages:
      - libboost-all-dev
      - libglew-dev
      - xorg
      - xorg-dev
      - libglu1-mesa-dev

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - git clone https://github.com/glfw/glfw.git
  - cd glfw
  - mkdir build
  - cd build
  - cmake ..
  - sudo make install
  - sudo ldconfig

script:
  - cd ../..
  - cmake .
  - make
