sudo: required

language: cpp

notifications:
  email: false

addons:
  apt:
    packages:
#      - libboost-all-dev
#      - libglew-dev
#      - xorg
#      - xorg-dev
#      - libglu1-mesa-dev
      - python3-pip
      - python3-tk
      - python-opencv

install:
  - sudo -H python3 -m pip install numpy
  - sudo -H python3 -m pip install Pillow
  - sudo -H python3 -m pip install pytesseract
  - sudo -H python3 -m pip install opencv-python
#  - git clone https://github.com/glfw/glfw.git
#  - cd glfw
#  - mkdir build
#  - cd build
#  - cmake ..
#  - sudo make install
#  - sudo ldconfig

script:
#  - cd ../..
  - cmake .
  - make
