sudo: required

language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - ubuntu-sdk-team
          packages:
            - cppcheck
            - clang-format-3.9
            - g++-5
            - libboost-all-dev
            - libglew-dev
            - xorg
            - xorg-dev
            - libglu1-mesa-dev
            - libopencv-dev
            - qtbase5-dev
            - qt5-default
            - libqt5webkit5-dev
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - ubuntu-sdk-team
          packages:
            - cppcheck
            - clang-format-3.9
            - g++-6
            - libboost-all-dev
            - libglew-dev
            - xorg
            - xorg-dev
            - libglu1-mesa-dev
            - libopencv-dev
            - qtbase5-dev
            - qt5-default
            - libqt5webkit5-dev
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

notifications:
  email: false

before_install:
  - git submodule update --init --recursive
  - eval "${MATRIX_EVAL}"

install:
  - git clone https://github.com/glfw/glfw.git
  - cd glfw
  - mkdir build
  - cd build
  - cmake -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX ..
  - sudo make install -j${nproc}
  - sudo ldconfig

script:
  - cd ../..
  - mkdir build && cd build
  - cmake -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX ..
  - make -j${nproc}
  - ctest
